# Generated by Django 4.2.3 on 2023-09-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baiboly", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="trad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bbl_m", models.CharField(max_length=20)),
                ("bbl_fr", models.CharField(max_length=20)),
            ],
        ),
    ]
