# Generated by Django 4.2.3 on 2023-09-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baiboly", "0002_trad"),
    ]

    operations = [
        migrations.AddField(
            model_name="trad",
            name="chpt",
            field=models.CharField(default="", max_length=5),
            preserve_default=False,
        ),
    ]
