# Generated by Django 4.2.3 on 2023-09-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baiboly", "0004_alter_vrs_baibl_bible_vrs"),
    ]

    operations = [
        migrations.AddField(
            model_name="vrs_baibl",
            name="nbr_vrs",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
