# Generated by Django 4.2.3 on 2023-09-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baiboly", "0005_vrs_baibl_nbr_vrs"),
    ]

    operations = [
        migrations.CreateModel(
            name="baiboly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bible", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "content_bible",
                    models.CharField(blank=True, max_length=50000, null=True),
                ),
            ],
        ),
    ]
