# Generated by Django 4.2.7 on 2023-12-24 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lesona", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="lesona", name="SousTitre",),
        migrations.CreateModel(
            name="sousTitre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sousTitre", models.CharField(max_length=1000)),
                (
                    "titre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lesona.lesona"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="fanazavana",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fanazavana", models.CharField(max_length=10000)),
                (
                    "sousTitre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lesona.soustitre",
                    ),
                ),
            ],
        ),
    ]
