# Generated by Django 4.2.7 on 2023-12-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lesona", "0002_remove_lesona_soustitre_soustitre_fanazavana"),
    ]

    operations = [
        migrations.AddField(
            model_name="fanazavana",
            name="tokoSyAndininy",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
