# Generated by Django 4.2.7 on 2023-12-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lesona", "0003_fanazavana_tokosyandininy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fanazavana",
            name="fanazavana",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="soustitre",
            name="sousTitre",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
