# Generated by Django 4.2.7 on 2023-12-24 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lesona", "0004_alter_fanazavana_fanazavana_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fanazavana",
            name="sousTitre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lesona.soustitre",
            ),
        ),
        migrations.AlterField(
            model_name="soustitre",
            name="titre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lesona.lesona",
            ),
        ),
    ]
