# Generated by Django 4.2.7 on 2023-11-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="fhrn_ajout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Titre", models.CharField(max_length=1000)),
                ("fhrn_mod", models.TextField()),
                ("ord_dif", models.CharField(max_length=1000)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="fhrn_mod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Titre", models.CharField(max_length=1000)),
                ("fhrn_mod", models.TextField()),
                ("ord_dif", models.CharField(max_length=1000)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="fihirana1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Titre", models.CharField(max_length=100)),
                ("Content", models.TextField()),
                ("ord_diff", models.CharField(max_length=1000)),
                ("etat", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="fihirana2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Titre", models.CharField(max_length=1000)),
                ("Content", models.TextField()),
                ("ord_diff", models.CharField(max_length=1000)),
                ("etat", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="list_fihirana1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Range_file", models.IntegerField()),
                ("Clés", models.CharField(max_length=10)),
                ("Transpose", models.IntegerField()),
                ("Titre", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="list_fihirana2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Range_file", models.IntegerField()),
                ("Clés", models.CharField(max_length=10)),
                ("Transpose", models.IntegerField()),
                ("Titre", models.CharField(max_length=1000)),
            ],
        ),
    ]
