# Generated by Django 4.2.7 on 2023-11-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fihirana", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="list_fihirana2",
            name="etat",
            field=models.BooleanField(default=False),
        ),
    ]
