# Generated by Django 4.2.7 on 2023-11-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fihirana", "0002_list_fihirana2_etat"),
    ]

    operations = [
        migrations.AddField(
            model_name="list_fihirana1",
            name="etat",
            field=models.BooleanField(default=False),
        ),
    ]
