# Generated by Django 4.2.7 on 2023-11-10 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fihirana", "0003_list_fihirana1_etat"),
    ]

    operations = [
        migrations.RemoveField(model_name="list_fihirana1", name="etat",),
    ]
