# Generated by Django 4.2.7 on 2023-11-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fihirana", "0005_remove_fihirana1_etat_remove_fihirana2_etat_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="list_fihirana_ajout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Range_file", models.IntegerField()),
                ("Clés", models.CharField(max_length=10)),
                ("Transpose", models.IntegerField()),
                ("Titre", models.CharField(max_length=1000)),
                ("etat", models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name="fhrn_ajout", old_name="fhrn_mod", new_name="content",
        ),
    ]
