# Generated by Django 4.2.7 on 2023-11-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fihirana", "0007_alter_list_fihirana_ajout_titre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list_fihirana_ajout",
            name="Clés",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="list_fihirana_ajout",
            name="Range_file",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="list_fihirana_ajout",
            name="Transpose",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
