# Generated by Django 4.2.7 on 2023-11-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fihirana", "0008_alter_list_fihirana_ajout_clés_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fhrn_ajout",
            name="Clés",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="fhrn_ajout",
            name="Range_file",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fhrn_ajout",
            name="Transpose",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
