# Generated by Django 4.2.7 on 2023-11-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fihirana", "0009_fhrn_ajout_clés_fhrn_ajout_range_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list_fihirana_ajout",
            name="Titre",
            field=models.CharField(max_length=1000),
        ),
    ]
